### ISSUE TITLE
Utilize TPW Furniture

### ISSUE THREAD

**Issue by mcrow900** [ArmaAchilles/AresModAchillesExpansion#171]
[Request]

**Mods:**
```
- CBA_A3
- AresModAchillesExpansion
```

**Description:**
- However instead of having it automatically spawn and despawn furniture as player gets close or goes away, just allow player to choose Range or Nearest building selection. I made a rough workup that allows spawn and delete that seems to work, but it has severe limitations such as furniture not being able to be deleted if building is damaged.   
I think the best solution would be to make it to spawn only and make the items add-able to Zeus.

**Comment by CreepPork** [comment]
Please attach the code you had created to this issue. It would be fantastic if you would create a PR as it's easier to work with some code rather than not having anything.

Also, don't TPW scripts have a license of some sorts? We can't just nick other peoples code without looking into the license itself.

**Comment by mcrow900** [comment]
https://pastebin.com/9L6PyzUJ  
I believe TPW license just requires acknowledgement of original owner and the derivative made public.

**Comment by oOKexOo** [comment]
closed in favour of #252
