### ISSUE TITLE
Garrison issues

### ISSUE THREAD

**Issue by unhappytroll** [ArmaAchilles/AresModAchillesExpansion#37]
1. If garrison module thinks that there is no room in a structure, it place remaining units in closest building (even not military) - which may be long way off. F.e. garrisoning fire team into cargo post results for two remaining units to fly to somewhere in the nearest town. Is there no distance checks? May be better do not move this units at all.

2. Sandbag bunkers are not working as a garrison points.

**Comment by Grezvany13** [comment]
> 1. If garrison module thinks that there is no room in a structure, it place remaining units in closest building (even not military) - which may be long way off. F.e. garrisoning fire team into cargo post results for two remaining units to fly to somewhere in the nearest town. Is there no distance checks? May be better do not move this units at all.

The Garrison Module currently uses a 150 meter radius around the unit(s) to find a single building in which it will try to place all units, if this building is full it will try to find the closest buildings within this same radius to fill out the group.
So it should always be within a 150 meter radius, which can be at the other side of a small village.

There currently is a modification of the garrison script which will check the size of the group before trying to find a building. If the group is too big (8 units or more), it will try to evenly spread the units over multiple buildings instead of put everything in 1 and then move the leftovers elsewhere.
This modification should be in the next version of AresAchilles (I hope ;))

> 2. Sandbag bunkers are not working as a garrison points.

This is a "missing feature" of ArmA 3. The Garrison Module uses a script which searches for (pre-defined) unit positions within a building (using [buildingPos](https://community.bistudio.com/wiki/buildingPos)). Usually this is at windows and near doors.
Since sandbags don't have a pre-defined position for (AI) units to use, the script won't be able to find a suitable position and therefor won't work with the Garrison Module.

**Comment by unhappytroll** [comment]
> The Garrison Module currently uses a 150 meter radius 
I should've posted a link to video, I believe. But ok, i've tested it in VR. Yes, it works as described and even worse - f.e., only sentry team (2 men) is fully garrisoned cargo post, fireteam (4 men) put only leader in it. I think there should be 2 tunable parameters - how max far it should place men (10-150 m), and how many men it should stuff in one building (in numbers - or in percentage of available positions) . At least it should have made Zeus able to fully populate HQ or big cargo post instead manual placement of units after some swear words.

> Since sandbags don't have a pre-defined position

This is indeed strange. Because in big bunker you _can_ assign bots to positions - manually, as a team commander (F2-F4/F8 - Move there).  So there is predefined positions. How about [BIS_fnc_buildingPositions](https://community.bistudio.com/wiki/BIS_fnc_buildingPositions) ?

**Comment by oOKexOo** [comment]
@Grezvany13 
Your modification should already be present in version 0.0.4.

@unhappytroll 
1) I like the idea of two additional parameters (assigned in #33).
2) At the end of the day, functions are just based on script commands and thus we go back to [buildingPos](https://community.bistudio.com/wiki/buildingPos).

**Comment by Grezvany13** [comment]
I did some testing in-game and found out the issue of objects not being used by the Garrison Module:

1) Not all object in ArmA 3 have predefined positions.
Eg. Bunker Tower, H-Barrier Tower, H-Barrier Wall, sandbags and walls

2) Not all objects are defined as "housing", and therefor not seen by the garrison script.
Eg. Bunker (Large) and Bunker (Small)

3) Some object do have a predefined position, even when it doesn't make sense.
Eg. Canal Wall (Stairs)

The issue is not caused by buidlingPos (or BIS_fnc_buildingPositions, since return the same values) but due [nearestBuilding](https://community.bistudio.com/wiki/nearestBuilding). This function only searches for objects which are in the "House" class, while some object (like the bunkers) are not.

A solution would be to use `_buildingsArray = nearestObjects [_center, ["building"], _buildingRadius];` in [fn_ZenOccupyHouse.sqf](https://github.com/oOKexOo/AresModAchillesExpansion/blob/master/%40AresModAchillesExpansion/addons/functions_f_ares/features/fn_ZenOccupyHouse.sqf#L43) at line 43-47.

Although I didn't test the impact, but I suspect it will be a bit slower due the fact that there are more "buildings" then just "houses", but I guess this can be negleted since it's just a single use action.

**Comment by unhappytroll** [comment]
probably there whould be some bugs, 'cause that part of definition of "building" - "and contains a path LOD".  Not every building may contain it (as you state in 1.). But the list is somewhat weird, f.e. H-Barriers has positions, that can be pointed to. And even some sandbags like short wall and wall end.

**Comment by oOKexOo** [comment]
Thx Grezvany13. I didn't think about that being the issue. So I just have to come up with a test to identify whether building positions are avialable or not for the specific object.

@unhappytroll 
I now have both your requests assigned in #33.

**Comment by oOKexOo** [comment]
I switched the searching pattern "house" to "building" in V.0.0.5. Let's see if we get better results.
The additional options for the module have to wait for a later update (probably 0.0.6).

**Comment by unhappytroll** [comment]
well, it behaves better, but now some strange effects become visible. 
http://imgur.com/a/BtRpm

looks like game did not make difference between internal and external positions

**Comment by oOKexOo** [comment]
Thx for the note. The behaviour is indeed strange. The work on the garrison modules is still in progress.
